// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Request.Infrastructure.Persistence;

#nullable disable

namespace Request.Infrastructure.Migrations
{
    [DbContext(typeof(RequestDbContext))]
    [Migration("20260302180847_AddGenericRequests")]
    partial class AddGenericRequests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Request.Domain.AggregatesModel.ExportAirRequestAggregate.ExportAirRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AirlineId")
                        .HasColumnType("uuid");

                    b.Property<string>("AirlineName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("ChargeableWeightKg")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("ConsigneeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConsigneeName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid?>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("DangerousGoods")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("DepartmentName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DescriptionOfGoods")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("DestinationName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("DestinationTerminalId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DispatchDateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DispatchDateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ExtremelyUrgent")
                        .HasColumnType("boolean");

                    b.Property<string>("GatewayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("GatewayTerminalId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("GrossWeightKg")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LogisticianId")
                        .HasColumnType("uuid");

                    b.Property<string>("LogisticianName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ManagerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("MyCustomerTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("MyCustomerTypeName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int?>("NumberOfPackages")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PriceStandard")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PriceWithVat")
                        .HasColumnType("numeric");

                    b.Property<bool?>("QuotationSent")
                        .HasColumnType("boolean");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("RequestPurposeId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestPurposeName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ShipperId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShipperName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("SourceOfRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceOfRequestName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("StatusName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ToAnswerUntilDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UnloadingDateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UnloadingDateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VatRate")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ViaPort2Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ViaPort2TerminalId")
                        .HasColumnType("uuid");

                    b.Property<string>("ViaPortName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ViaPortTerminalId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("VolumeCbm")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("ExportAirRequests", (string)null);
                });

            modelBuilder.Entity("Request.Domain.AggregatesModel.ExportAirRequestAggregate.ExportAirRequestDimension", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExportAirRequestId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Length")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal?>("VolumeCbm")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Width")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ExportAirRequestId");

                    b.ToTable("ExportAirRequestDimensions", (string)null);
                });

            modelBuilder.Entity("Request.Domain.AggregatesModel.ImportAirRequestAggregate.ImportAirRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AirlineId")
                        .HasColumnType("uuid");

                    b.Property<string>("AirlineName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("ChargeableWeightKg")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("ConsigneeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConsigneeName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid?>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("DangerousGoods")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("DepartmentName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DescriptionOfGoods")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("DestinationName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("DestinationTerminalId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DispatchDateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DispatchDateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ExtremelyUrgent")
                        .HasColumnType("boolean");

                    b.Property<string>("GatewayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("GatewayTerminalId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("GrossWeightKg")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LogisticianId")
                        .HasColumnType("uuid");

                    b.Property<string>("LogisticianName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ManagerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("MyCustomerTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("MyCustomerTypeName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int?>("NumberOfPackages")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PriceStandard")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PriceWithVat")
                        .HasColumnType("numeric");

                    b.Property<bool?>("QuotationSent")
                        .HasColumnType("boolean");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("RequestPurposeId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestPurposeName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ShipperId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShipperName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("SourceOfRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceOfRequestName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("StatusName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ToAnswerUntilDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UnloadingDateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UnloadingDateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VatRate")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ViaPort2Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ViaPort2TerminalId")
                        .HasColumnType("uuid");

                    b.Property<string>("ViaPortName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ViaPortTerminalId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("VolumeCbm")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("ImportAirRequests", (string)null);
                });

            modelBuilder.Entity("Request.Domain.AggregatesModel.ImportAirRequestAggregate.ImportAirRequestDimension", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ImportAirRequestId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Length")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal?>("VolumeCbm")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Width")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ImportAirRequestId");

                    b.ToTable("ImportAirRequestDimensions", (string)null);
                });

            modelBuilder.Entity("Request.Domain.AggregatesModel.RequestAggregate.RequestDimension", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Length")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("VolumeCbm")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Width")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("RequestDimensions", (string)null);
                });

            modelBuilder.Entity("Request.Domain.AggregatesModel.RequestAggregate.RequestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CarrierId")
                        .HasColumnType("uuid");

                    b.Property<string>("CarrierName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("ChargeableWeightKg")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("ConsigneeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConsigneeName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid?>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("DangerousGoods")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("DepartmentName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DescriptionOfGoods")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("DestinationName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("DestinationTerminalId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DispatchDateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DispatchDateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ExtremelyUrgent")
                        .HasColumnType("boolean");

                    b.Property<string>("GatewayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("GatewayTerminalId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("GrossWeightKg")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LogisticianId")
                        .HasColumnType("uuid");

                    b.Property<string>("LogisticianName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ManagerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("MyCustomerTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("MyCustomerTypeName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int?>("NumberOfPackages")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PriceStandard")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PriceWithVat")
                        .HasColumnType("numeric");

                    b.Property<bool?>("QuotationSent")
                        .HasColumnType("boolean");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("RequestPurposeId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestPurposeName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("RequestTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ShipperId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShipperName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("SourceOfRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceOfRequestName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("StatusName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ToAnswerUntilDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UnloadingDateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UnloadingDateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VatRate")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ViaPort2Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ViaPort2TerminalId")
                        .HasColumnType("uuid");

                    b.Property<string>("ViaPortName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ViaPortTerminalId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("VolumeCbm")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("RequestTypeId");

                    b.ToTable("Requests", (string)null);
                });

            modelBuilder.Entity("Request.Domain.AggregatesModel.RequestAggregate.RequestType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CarrierApiPath")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CarrierLabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RequestNumberPrefix")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("RequestTypes", (string)null);
                });

            modelBuilder.Entity("Request.Domain.AggregatesModel.RequestNegotiationAggregate.RequestNegotiation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Question")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Result")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("WayOfNegotiationId")
                        .HasColumnType("uuid");

                    b.Property<string>("WayOfNegotiationName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("RequestNegotiations", (string)null);
                });

            modelBuilder.Entity("Request.Domain.AggregatesModel.SaleAggregate.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CargoName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("CargoSize")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("CargoVolume")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CargoWeight")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("CarrierId")
                        .HasColumnType("uuid");

                    b.Property<string>("CarrierName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DealValue")
                        .HasColumnType("numeric");

                    b.Property<string>("DealValueCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasAir")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasRail")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasRoad")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasSea")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LoadingPlace")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ManagerSellerName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("PriceProposal")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SaleListStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("SaleStatusId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UnloadingPlace")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SaleStatusId");

                    b.ToTable("Sales", (string)null);
                });

            modelBuilder.Entity("Request.Domain.AggregatesModel.SaleStatusAggregate.SaleStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SaleStatuses", (string)null);
                });

            modelBuilder.Entity("Request.Domain.AggregatesModel.ExportAirRequestAggregate.ExportAirRequestDimension", b =>
                {
                    b.HasOne("Request.Domain.AggregatesModel.ExportAirRequestAggregate.ExportAirRequest", null)
                        .WithMany()
                        .HasForeignKey("ExportAirRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Request.Domain.AggregatesModel.ImportAirRequestAggregate.ImportAirRequestDimension", b =>
                {
                    b.HasOne("Request.Domain.AggregatesModel.ImportAirRequestAggregate.ImportAirRequest", null)
                        .WithMany()
                        .HasForeignKey("ImportAirRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Request.Domain.AggregatesModel.RequestAggregate.RequestDimension", b =>
                {
                    b.HasOne("Request.Domain.AggregatesModel.RequestAggregate.RequestEntity", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Request.Domain.AggregatesModel.RequestAggregate.RequestEntity", b =>
                {
                    b.HasOne("Request.Domain.AggregatesModel.RequestAggregate.RequestType", null)
                        .WithMany()
                        .HasForeignKey("RequestTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Request.Domain.AggregatesModel.SaleAggregate.Sale", b =>
                {
                    b.HasOne("Request.Domain.AggregatesModel.SaleStatusAggregate.SaleStatus", "SaleStatus")
                        .WithMany()
                        .HasForeignKey("SaleStatusId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SaleStatus");
                });
#pragma warning restore 612, 618
        }
    }
}
