// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Request.Infrastructure.Persistence;

#nullable disable

namespace Request.Infrastructure.Migrations
{
    [DbContext(typeof(RequestDbContext))]
    partial class RequestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Request.Domain.AggregatesModel.CommercialOfferAggregate.CommercialOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttachedFileReference")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("BasedOnCalculation")
                        .HasColumnType("boolean");

                    b.Property<string>("Comments")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DocumentSourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("ProvideClientAccess")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("TemplateName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("CommercialOffers", (string)null);
                });

            modelBuilder.Entity("Request.Domain.AggregatesModel.CommercialOfferAggregate.CommercialOfferSelectedProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommercialOfferId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PriceProposalId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PriceProposalId");

                    b.HasIndex("CommercialOfferId", "PriceProposalId")
                        .IsUnique();

                    b.ToTable("CommercialOfferSelectedProposals", (string)null);
                });

            modelBuilder.Entity("Request.Domain.AggregatesModel.PriceProposalAggregate.PriceProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CarrierCurrencyCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid?>("CarrierCurrencyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CarrierId")
                        .HasColumnType("uuid");

                    b.Property<string>("CarrierName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal?>("CarrierRate")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CarrierRateWithVat")
                        .HasColumnType("numeric");

                    b.Property<string>("CarrierVatRateCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("CarrierVatRateId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientCurrencyCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid?>("ClientCurrencyId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ClientPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ClientPriceWithVat")
                        .HasColumnType("numeric");

                    b.Property<string>("ClientVatRateCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("ClientVatRateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comments")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Expense")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal?>("Profit")
                        .HasColumnType("numeric");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Route")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("SeparateLineInInvoice")
                        .HasColumnType("boolean");

                    b.Property<string>("TemplateName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TypeOfService")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("PriceProposals", (string)null);
                });

            modelBuilder.Entity("Request.Domain.AggregatesModel.PriceProposalAggregate.PriceProposalCargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DescriptionOfGoods")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IncludeInsurance")
                        .HasColumnType("boolean");

                    b.Property<string>("PackageType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("PriceProposalId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PriceProposalId");

                    b.ToTable("PriceProposalCargos", (string)null);
                });

            modelBuilder.Entity("Request.Domain.AggregatesModel.RequestAggregate.RequestDimension", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Length")
                        .HasColumnType("numeric");

                    b.Property<string>("PackageType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("VolumeCbm")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Width")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("RequestDimensions", (string)null);
                });

            modelBuilder.Entity("Request.Domain.AggregatesModel.RequestAggregate.RequestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CarrierId")
                        .HasColumnType("uuid");

                    b.Property<string>("CarrierName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("ChargeableWeightKg")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("ConsigneeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConsigneeName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid?>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("DangerousGoods")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("DepartmentName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DescriptionOfGoods")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("DestinationName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("DestinationTerminalId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DispatchDateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DispatchDateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ExtremelyUrgent")
                        .HasColumnType("boolean");

                    b.Property<string>("GatewayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("GatewayTerminalId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("GrossWeightKg")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LogisticianId")
                        .HasColumnType("uuid");

                    b.Property<string>("LogisticianName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ManagerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("MyCustomerTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("MyCustomerTypeName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int?>("NumberOfPackages")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PriceStandard")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PriceWithVat")
                        .HasColumnType("numeric");

                    b.Property<bool?>("QuotationSent")
                        .HasColumnType("boolean");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("RequestPurposeId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestPurposeName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("RequestTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ShipperId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShipperName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("SourceOfRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceOfRequestName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("StationOfDeliveryName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("StationOfDeliveryTerminalId")
                        .HasColumnType("uuid");

                    b.Property<string>("StatusName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ToAnswerUntilDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransitPortName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("TransitPortTerminalId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UnloadingDateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UnloadingDateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VatRate")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ViaPort2Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ViaPort2TerminalId")
                        .HasColumnType("uuid");

                    b.Property<string>("ViaPortName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ViaPortTerminalId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("VolumeCbm")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("RequestTypeId");

                    b.ToTable("Requests", (string)null);
                });

            modelBuilder.Entity("Request.Domain.AggregatesModel.RequestAggregate.RequestType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CarrierApiPath")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CarrierLabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RequestNumberPrefix")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("SubType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("RequestTypes", (string)null);
                });

            modelBuilder.Entity("Request.Domain.AggregatesModel.RequestAggregate.RequestVas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid?>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExecutionPlace")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Total")
                        .HasColumnType("numeric");

                    b.Property<string>("Uom")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("VasId")
                        .HasColumnType("uuid");

                    b.Property<string>("VasName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("RequestVas", (string)null);
                });

            modelBuilder.Entity("Request.Domain.AggregatesModel.RequestCommentAggregate.RequestComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comments")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("RequestComments", (string)null);
                });

            modelBuilder.Entity("Request.Domain.AggregatesModel.RequestNegotiationAggregate.RequestNegotiation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Question")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Result")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("WayOfNegotiationId")
                        .HasColumnType("uuid");

                    b.Property<string>("WayOfNegotiationName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("RequestNegotiations", (string)null);
                });

            modelBuilder.Entity("Request.Domain.AggregatesModel.SaleAggregate.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CargoName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("CargoSize")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("CargoVolume")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CargoWeight")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("CarrierId")
                        .HasColumnType("uuid");

                    b.Property<string>("CarrierName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DealValue")
                        .HasColumnType("numeric");

                    b.Property<string>("DealValueCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasAir")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasRail")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasRoad")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasSea")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LoadingPlace")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ManagerSellerName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("PriceProposal")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SaleListStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("SaleStatusId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UnloadingPlace")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SaleStatusId");

                    b.ToTable("Sales", (string)null);
                });

            modelBuilder.Entity("Request.Domain.AggregatesModel.SaleStatusAggregate.SaleStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SaleStatuses", (string)null);
                });

            modelBuilder.Entity("Request.Domain.AggregatesModel.CommercialOfferAggregate.CommercialOffer", b =>
                {
                    b.HasOne("Request.Domain.AggregatesModel.RequestAggregate.RequestEntity", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Request.Domain.AggregatesModel.CommercialOfferAggregate.CommercialOfferSelectedProposal", b =>
                {
                    b.HasOne("Request.Domain.AggregatesModel.CommercialOfferAggregate.CommercialOffer", "CommercialOffer")
                        .WithMany("SelectedProposals")
                        .HasForeignKey("CommercialOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Request.Domain.AggregatesModel.PriceProposalAggregate.PriceProposal", "PriceProposal")
                        .WithMany()
                        .HasForeignKey("PriceProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommercialOffer");

                    b.Navigation("PriceProposal");
                });

            modelBuilder.Entity("Request.Domain.AggregatesModel.PriceProposalAggregate.PriceProposal", b =>
                {
                    b.HasOne("Request.Domain.AggregatesModel.RequestAggregate.RequestEntity", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Request.Domain.AggregatesModel.PriceProposalAggregate.PriceProposalCargo", b =>
                {
                    b.HasOne("Request.Domain.AggregatesModel.PriceProposalAggregate.PriceProposal", null)
                        .WithMany("CargoItems")
                        .HasForeignKey("PriceProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Request.Domain.AggregatesModel.RequestAggregate.RequestDimension", b =>
                {
                    b.HasOne("Request.Domain.AggregatesModel.RequestAggregate.RequestEntity", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Request.Domain.AggregatesModel.RequestAggregate.RequestEntity", b =>
                {
                    b.HasOne("Request.Domain.AggregatesModel.RequestAggregate.RequestType", null)
                        .WithMany()
                        .HasForeignKey("RequestTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Request.Domain.AggregatesModel.RequestAggregate.RequestVas", b =>
                {
                    b.HasOne("Request.Domain.AggregatesModel.RequestAggregate.RequestEntity", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Request.Domain.AggregatesModel.RequestCommentAggregate.RequestComment", b =>
                {
                    b.HasOne("Request.Domain.AggregatesModel.RequestAggregate.RequestEntity", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Request.Domain.AggregatesModel.SaleAggregate.Sale", b =>
                {
                    b.HasOne("Request.Domain.AggregatesModel.SaleStatusAggregate.SaleStatus", "SaleStatus")
                        .WithMany()
                        .HasForeignKey("SaleStatusId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SaleStatus");
                });

            modelBuilder.Entity("Request.Domain.AggregatesModel.CommercialOfferAggregate.CommercialOffer", b =>
                {
                    b.Navigation("SelectedProposals");
                });

            modelBuilder.Entity("Request.Domain.AggregatesModel.PriceProposalAggregate.PriceProposal", b =>
                {
                    b.Navigation("CargoItems");
                });
#pragma warning restore 612, 618
        }
    }
}
