<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Request.API</RootNamespace>
    <UserSecretsId>req-1a2b3c4d-5e6f-7890-abcd-ef1234567890</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
    <PackageReference Include="MrStyx.API" Version="1.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql" Version="10.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\shared\AzShipping.ApiSecurity\AzShipping.ApiSecurity.csproj" />
    <ProjectReference Include="..\..\Accounting\Accounting.Domain\Accounting.Domain.csproj" />
    <ProjectReference Include="..\Request.Domain\Request.Domain.csproj" />
    <ProjectReference Include="..\Request.Application\Request.Application.csproj" />
    <ProjectReference Include="..\Request.Infrastructure\Request.Infrastructure.csproj" />
  </ItemGroup>
</Project>
