namespace Settings.Application.DTOs.Company;

public record CreateCompanyDto(
    string Name,
    string? NameFull = null,
    string? DirectorsFullName = null,
    string? InTheNameOfWhom = null,
    Guid? WorkerPostId = null,
    string? Post = null,
    string? VatRate = null,
    Guid? PricingTypeId = null,
    string? PricingType = null,
    string? CompanyPrefix = null,
    string? CompanyCodeType = null,
    string? CompanyCode = null,
    string? VatCode = null,
    string? Rrc = null,
    string? CorrespondentAccount = null,
    string? Okpo = null,
    string? Ogrn = null,
    Guid? CountryId = null,
    Guid? StateId = null,
    Guid? CityId = null,
    string? Address = null,
    string? PostCode = null,
    string? Telephone = null,
    string? Fax = null,
    string? Email = null,
    string? Website = null,
    bool IsMainCompany = false,
    Guid? CorrespondentCountryId = null,
    Guid? CorrespondentStateId = null,
    Guid? CorrespondentCityId = null,
    string? CorrespondentAddress = null,
    string? CorrespondentPostCode = null,
    string? CorrespondentTelephone = null,
    string? CorrespondentFax = null,
    string? CorrespondentEmail = null,
    string? CorrespondentWebsite = null,
    bool IsActive = true,
    IReadOnlyList<CreateCompanyBankAccountDto>? BankAccounts = null,
    IReadOnlyList<CreateCompanySignatureDto>? Signatures = null);
