<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Settings.Domain</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MrStyx.Domain" Version="1.0.0" />
    <PackageReference Include="Azshipping.Auth" Version="1.0.0" />
  </ItemGroup>
</Project>
