// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Operation.Infrastructure.Persistence;

#nullable disable

namespace Operation.Infrastructure.Migrations
{
    [DbContext(typeof(OperationDbContext))]
    [Migration("20260329122408_ExportSeaBreakbulkVas")]
    partial class ExportSeaBreakbulkVas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Operation.Domain.AggregatesModel.OperationAggregate.LogisticsOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("AgentName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("CargoAdditionalInformation")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("CargoName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("CargoTransportTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("CargoTransportTypeName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("CarrierId")
                        .HasColumnType("uuid");

                    b.Property<string>("CarrierName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("ChargeableWeightKg")
                        .HasColumnType("numeric");

                    b.Property<string>("ClientOrderNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("ConsigneeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConsigneeName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ConsignmentCurrencyCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid?>("ConsignmentCurrencyId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ConsignmentPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid?>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("DangerousGoods")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("DeferredPaymentConditionId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeferredPaymentConditionName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("DeferredPaymentDays")
                        .HasColumnType("integer");

                    b.Property<Guid?>("DeliveryCityId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeliveryCityName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("DeliveryCountryId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeliveryCountryName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("DeliveryStateId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeliveryStateName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DeliveryZipCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("DepartmentName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DescriptionOfGoods")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("DestinationName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("DestinationTerminalId")
                        .HasColumnType("uuid");

                    b.Property<string>("FlightNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FreightPrepaidCollect")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GatewayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("GatewayTerminalId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("GrossWeightKg")
                        .HasColumnType("numeric");

                    b.Property<bool>("IncludeDelivery")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncludePickup")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncludeVas")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("IncotermId")
                        .HasColumnType("uuid");

                    b.Property<string>("IncotermName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LoadingMethodId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoadingMethodName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("LogisticianId")
                        .HasColumnType("uuid");

                    b.Property<string>("LogisticianName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MainHarmonize")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ManagerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Mawb")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ModalType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MoveTypeName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("MyCustomerClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("MyCustomerName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("MyCustomerParty")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("NotesToBePrinted")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("NumberOfPackages")
                        .HasColumnType("integer");

                    b.Property<string>("OceanBillOfLading")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OperationNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OperationTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("OtherPrepaidCollect")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("PickupCityId")
                        .HasColumnType("uuid");

                    b.Property<string>("PickupCityName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("PickupCountryId")
                        .HasColumnType("uuid");

                    b.Property<string>("PickupCountryName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("PickupStateId")
                        .HasColumnType("uuid");

                    b.Property<string>("PickupStateName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PickupZipCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PortOfDeliveryName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("PortOfDeliveryTerminalId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("PriceStandard")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PriceWithVat")
                        .HasColumnType("numeric");

                    b.Property<string>("PricingMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Reference1")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Reference2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("SalesmanId")
                        .HasColumnType("uuid");

                    b.Property<string>("SalesmanName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ShipperId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShipperName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StartTime")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("TemplateName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VatRate")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("VesselId")
                        .HasColumnType("uuid");

                    b.Property<string>("VesselName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ViaPort2Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ViaPort2TerminalId")
                        .HasColumnType("uuid");

                    b.Property<string>("ViaPortName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ViaPortTerminalId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("VolumeCbm")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("OperationTypeId");

                    b.ToTable("Operations", (string)null);
                });

            modelBuilder.Entity("Operation.Domain.AggregatesModel.OperationAggregate.OperationDimension", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Length")
                        .HasColumnType("numeric");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PackageType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal?>("VolumeCbm")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Width")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("OperationId");

                    b.ToTable("OperationDimensions", (string)null);
                });

            modelBuilder.Entity("Operation.Domain.AggregatesModel.OperationAggregate.OperationPackageLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PackageType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OperationId");

                    b.ToTable("OperationPackageLines", (string)null);
                });

            modelBuilder.Entity("Operation.Domain.AggregatesModel.OperationAggregate.OperationType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CarrierApiPath")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CarrierLabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OperationNumberPrefix")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("SubType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("OperationTypes", (string)null);
                });

            modelBuilder.Entity("Operation.Domain.AggregatesModel.OperationAggregate.OperationVas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid?>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExecutionPlace")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Total")
                        .HasColumnType("numeric");

                    b.Property<string>("Uom")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("VasId")
                        .HasColumnType("uuid");

                    b.Property<string>("VasName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("OperationId");

                    b.ToTable("OperationVas", (string)null);
                });

            modelBuilder.Entity("Operation.Domain.AggregatesModel.OperationAggregate.LogisticsOperation", b =>
                {
                    b.HasOne("Operation.Domain.AggregatesModel.OperationAggregate.OperationType", null)
                        .WithMany()
                        .HasForeignKey("OperationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Operation.Domain.AggregatesModel.OperationAggregate.OperationDimension", b =>
                {
                    b.HasOne("Operation.Domain.AggregatesModel.OperationAggregate.LogisticsOperation", "Operation")
                        .WithMany("Dimensions")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("Operation.Domain.AggregatesModel.OperationAggregate.OperationPackageLine", b =>
                {
                    b.HasOne("Operation.Domain.AggregatesModel.OperationAggregate.LogisticsOperation", "Operation")
                        .WithMany("PackageLines")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("Operation.Domain.AggregatesModel.OperationAggregate.OperationVas", b =>
                {
                    b.HasOne("Operation.Domain.AggregatesModel.OperationAggregate.LogisticsOperation", "Operation")
                        .WithMany("VasItems")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("Operation.Domain.AggregatesModel.OperationAggregate.LogisticsOperation", b =>
                {
                    b.Navigation("Dimensions");

                    b.Navigation("PackageLines");

                    b.Navigation("VasItems");
                });
#pragma warning restore 612, 618
        }
    }
}
