// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Settings.Infrastructure.Persistence;

#nullable disable

namespace Settings.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SettingsDbContext))]
    [Migration("20260219185010_AddResultTypesAndFunnelResults")]
    partial class AddResultTypesAndFunnelResults
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Settings.Domain.AggregatesModel.BankAggregate.Bank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Branch")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PostCode")
                        .HasColumnType("text");

                    b.Property<string>("Swift")
                        .HasColumnType("text");

                    b.Property<string>("UnofficialName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Banks", (string)null);
                });

            modelBuilder.Entity("Settings.Domain.AggregatesModel.CarrierTypeAggregate.CarrierType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CarrierTypes", (string)null);
                });

            modelBuilder.Entity("Settings.Domain.AggregatesModel.ClientSegmentAggregate.ClientSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecondaryColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SegmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SegmentPriority")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ClientSegments", (string)null);
                });

            modelBuilder.Entity("Settings.Domain.AggregatesModel.DeferredPaymentConditionAggregate.DeferredPaymentCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullText")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("DeferredPaymentConditions", (string)null);
                });

            modelBuilder.Entity("Settings.Domain.AggregatesModel.DrivingLicenceCategoryAggregate.DrivingLicenceCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("DrivingLicenceCategories", (string)null);
                });

            modelBuilder.Entity("Settings.Domain.AggregatesModel.FunnelResultAggregate.FunnelResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ResultTypeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("ToNextStep")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ResultTypeId");

                    b.ToTable("FunnelResults", (string)null);
                });

            modelBuilder.Entity("Settings.Domain.AggregatesModel.LoadingMethodAggregate.LoadingMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("LoadingMethods", (string)null);
                });

            modelBuilder.Entity("Settings.Domain.AggregatesModel.LoadingMethodAggregate.LoadingMethodTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("LoadingMethodId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("LoadingMethodId");

                    b.ToTable("LoadingMethodTranslations", (string)null);
                });

            modelBuilder.Entity("Settings.Domain.AggregatesModel.PackagingAggregate.Packaging", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Packagings", (string)null);
                });

            modelBuilder.Entity("Settings.Domain.AggregatesModel.PackagingAggregate.PackagingTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("PackagingId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PackagingId");

                    b.ToTable("PackagingTranslations", (string)null);
                });

            modelBuilder.Entity("Settings.Domain.AggregatesModel.RequestPurposeAggregate.RequestPurpose", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("RequestPurposes", (string)null);
                });

            modelBuilder.Entity("Settings.Domain.AggregatesModel.RequestSourceAggregate.RequestSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("RequestSources", (string)null);
                });

            modelBuilder.Entity("Settings.Domain.AggregatesModel.ResultTypeAggregate.ResultType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ResultTypes", (string)null);
                });

            modelBuilder.Entity("Settings.Domain.AggregatesModel.SalesFunnelStatusAggregate.SalesFunnelStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("NumberOfDays")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ResponsibleManagerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("SendNotification")
                        .HasColumnType("boolean");

                    b.Property<bool>("SendToEmail")
                        .HasColumnType("boolean");

                    b.Property<int>("StatusPosition")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SalesFunnelStatuses", (string)null);
                });

            modelBuilder.Entity("Settings.Domain.AggregatesModel.TransportTypeAggregate.TransportType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAir")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRail")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRoad")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSea")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TransportTypes", (string)null);
                });

            modelBuilder.Entity("Settings.Domain.AggregatesModel.WayOfNegotiationAggregate.WayOfNegotiation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("WayOfNegotiations", (string)null);
                });

            modelBuilder.Entity("Settings.Domain.AggregatesModel.WayOfNegotiationAggregate.WayOfNegotiationTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("WayOfNegotiationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WayOfNegotiationId");

                    b.ToTable("WayOfNegotiationTranslations", (string)null);
                });

            modelBuilder.Entity("Settings.Domain.AggregatesModel.WorkerPostAggregate.WorkerPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("WorkerPosts", (string)null);
                });

            modelBuilder.Entity("Settings.Domain.AggregatesModel.WorkerPostAggregate.WorkerPostTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("WorkerPostId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkerPostId");

                    b.ToTable("WorkerPostTranslations", (string)null);
                });

            modelBuilder.Entity("Settings.Domain.AggregatesModel.FunnelResultAggregate.FunnelResult", b =>
                {
                    b.HasOne("Settings.Domain.AggregatesModel.ResultTypeAggregate.ResultType", "ResultType")
                        .WithMany()
                        .HasForeignKey("ResultTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ResultType");
                });

            modelBuilder.Entity("Settings.Domain.AggregatesModel.LoadingMethodAggregate.LoadingMethodTranslation", b =>
                {
                    b.HasOne("Settings.Domain.AggregatesModel.LoadingMethodAggregate.LoadingMethod", "LoadingMethod")
                        .WithMany("Translations")
                        .HasForeignKey("LoadingMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoadingMethod");
                });

            modelBuilder.Entity("Settings.Domain.AggregatesModel.PackagingAggregate.PackagingTranslation", b =>
                {
                    b.HasOne("Settings.Domain.AggregatesModel.PackagingAggregate.Packaging", "Packaging")
                        .WithMany("Translations")
                        .HasForeignKey("PackagingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Packaging");
                });

            modelBuilder.Entity("Settings.Domain.AggregatesModel.WayOfNegotiationAggregate.WayOfNegotiationTranslation", b =>
                {
                    b.HasOne("Settings.Domain.AggregatesModel.WayOfNegotiationAggregate.WayOfNegotiation", "WayOfNegotiation")
                        .WithMany("Translations")
                        .HasForeignKey("WayOfNegotiationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WayOfNegotiation");
                });

            modelBuilder.Entity("Settings.Domain.AggregatesModel.WorkerPostAggregate.WorkerPostTranslation", b =>
                {
                    b.HasOne("Settings.Domain.AggregatesModel.WorkerPostAggregate.WorkerPost", "WorkerPost")
                        .WithMany("Translations")
                        .HasForeignKey("WorkerPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkerPost");
                });

            modelBuilder.Entity("Settings.Domain.AggregatesModel.LoadingMethodAggregate.LoadingMethod", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Settings.Domain.AggregatesModel.PackagingAggregate.Packaging", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Settings.Domain.AggregatesModel.WayOfNegotiationAggregate.WayOfNegotiation", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Settings.Domain.AggregatesModel.WorkerPostAggregate.WorkerPost", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
