using MediatR;
using Quotes.Application.DTOs.Quote;
using Quotes.Application.Features.Quotes.Queries.GetQuoteById;
using Quotes.Application.Services;
using Quotes.Domain.AggregatesModel.QuoteAggregate;

namespace Quotes.Application.Features.Quotes.Commands.UpdateQuote;

public sealed class UpdateQuoteCommandHandler(
    IQuoteRepository repository,
    IQuoteTypeRepository typeRepository,
    IActionLogClient actionLogClient) : IRequestHandler<UpdateQuoteCommand, QuoteDto?>
{
    public async Task<QuoteDto?> Handle(UpdateQuoteCommand request, CancellationToken cancellationToken)
    {
        var entity = await repository.GetByIdAsync(request.Id, cancellationToken);
        if (entity == null) return null;
        var d = request.Dto;
        var now = DateTime.UtcNow;
        entity.QuoteTypeId = d.QuoteTypeId;
        entity.QuoteNumber = string.IsNullOrWhiteSpace(d.QuoteNumber) ? entity.QuoteNumber : d.QuoteNumber.Trim();
        entity.CompanyId = d.CompanyId;
        entity.CompanyName = d.CompanyName;
        entity.ManagerId = d.ManagerId;
        entity.ManagerName = d.ManagerName;
        entity.LogisticianId = d.LogisticianId;
        entity.LogisticianName = d.LogisticianName;
        entity.HandlerId = d.HandlerId;
        entity.HandlerName = d.HandlerName;
        entity.AccountManagerId = d.AccountManagerId;
        entity.AccountManagerName = d.AccountManagerName;
        entity.OpenedById = d.OpenedById;
        entity.OpenedByName = d.OpenedByName;
        entity.ManagerUserId = d.ManagerUserId;
        entity.HandlerUserId = d.HandlerUserId;
        entity.AccountManagerUserId = d.AccountManagerUserId;
        entity.OpenedByUserId = d.OpenedByUserId;
        entity.DepartmentId = d.DepartmentId;
        entity.DepartmentName = d.DepartmentName;
        entity.QuoteStatus = d.QuoteStatus;
        entity.ShipperId = d.ShipperId;
        entity.ShipperName = d.ShipperName;
        entity.ConsigneeId = d.ConsigneeId;
        entity.ConsigneeName = d.ConsigneeName;
        entity.MyCustomerTypeId = d.MyCustomerTypeId;
        entity.MyCustomerTypeName = d.MyCustomerTypeName;
        entity.RateType = d.RateType;
        entity.StartDate = d.StartDate;
        entity.Etd = d.Etd;
        entity.Eta = d.Eta;
        entity.IncotermId = d.IncotermId;
        entity.IncotermName = d.IncotermName;
        entity.ExpirationDays = d.ExpirationDays;
        entity.PurchaseFreeDays = d.PurchaseFreeDays;
        entity.SaleFreeDays = d.SaleFreeDays;
        entity.MoveTypeId = d.MoveTypeId;
        entity.MoveTypeName = d.MoveTypeName;
        entity.ExpirationDate = d.ExpirationDate;
        entity.CloseAutomaticallyDeclined = d.CloseAutomaticallyDeclined;
        entity.CloseAutomaticallyDeclinedDays = d.CloseAutomaticallyDeclinedDays;
        entity.AutomaticallyCloseDate = d.AutomaticallyCloseDate;
        entity.IncludeInsurance = d.IncludeInsurance ?? false;
        entity.InsuranceValue = d.InsuranceValue;
        entity.IsStackable = d.IsStackable ?? false;
        entity.IncludeImportDutyCharges = d.IncludeImportDutyCharges ?? false;
        entity.TransitTime = d.TransitTime;
        entity.IsFreighter = d.IsFreighter ?? false;
        entity.DepartureFrequency = d.DepartureFrequency;
        entity.ValueOfGoods = d.ValueOfGoods;
        entity.PriceStandard = d.PriceStandard;
        entity.RmbVwt = d.RmbVwt;
        entity.CurrencyId = d.CurrencyId;
        entity.CurrencyCode = d.CurrencyCode;
        entity.PriceWithVat = d.PriceWithVat;
        entity.MinVat = d.MinVat;
        entity.VatRate = d.VatRate;
        entity.VatNote = d.VatNote;
        entity.IncludePickup = d.IncludePickup ?? false;
        entity.PickupAddressId = d.PickupAddressId;
        entity.PickupCountryId = d.PickupCountryId;
        entity.PickupCountryName = d.PickupCountryName;
        entity.PickupStateId = d.PickupStateId;
        entity.PickupStateName = d.PickupStateName;
        entity.PickupCityId = d.PickupCityId;
        entity.PickupCityName = d.PickupCityName;
        entity.PickupZipCode = d.PickupZipCode;
        entity.GatewayTerminalId = d.GatewayTerminalId;
        entity.GatewayName = d.GatewayName;
        entity.ViaPortTerminalId = d.ViaPortTerminalId;
        entity.ViaPortName = d.ViaPortName;
        entity.DestinationTerminalId = d.DestinationTerminalId;
        entity.DestinationName = d.DestinationName;
        entity.ViaPort2TerminalId = d.ViaPort2TerminalId;
        entity.ViaPort2Name = d.ViaPort2Name;
        entity.CarrierId = d.CarrierId;
        entity.CarrierName = d.CarrierName;
        entity.MyPortTerminalId = d.MyPortTerminalId;
        entity.MyPortName = d.MyPortName;
        entity.MyPort2TerminalId = d.MyPort2TerminalId;
        entity.MyPort2Name = d.MyPort2Name;
        entity.PortOfDeliveryName = d.PortOfDeliveryName;
        entity.VasId = d.VasId;
        entity.IncludeVas = d.IncludeVas ?? false;
        entity.VasServiceName = d.VasServiceName;
        entity.ExecutionPlace = d.ExecutionPlace;
        entity.VasQuantity = d.VasQuantity;
        entity.VasUom = d.VasUom;
        entity.VasCurrencyCode = d.VasCurrencyCode;
        entity.VasTotal = d.VasTotal;
        entity.VasNotes = d.VasNotes;
        entity.IncludeDelivery = d.IncludeDelivery ?? false;
        entity.DeliveryAddressId = d.DeliveryAddressId;
        entity.DeliveryCountryId = d.DeliveryCountryId;
        entity.DeliveryCountryName = d.DeliveryCountryName;
        entity.DeliveryStateId = d.DeliveryStateId;
        entity.DeliveryStateName = d.DeliveryStateName;
        entity.DeliveryCityId = d.DeliveryCityId;
        entity.DeliveryCityName = d.DeliveryCityName;
        entity.DeliveryZipCode = d.DeliveryZipCode;
        entity.GrossWeightKg = d.GrossWeightKg;
        entity.VolumeCbm = d.VolumeCbm;
        entity.ChargeableWeightKg = d.ChargeableWeightKg;
        entity.NumberOfPackages = d.NumberOfPackages;
        entity.DangerousGoods = d.DangerousGoods ?? false;
        entity.DescriptionOfGoods = d.DescriptionOfGoods;
        entity.Quantity1 = d.Quantity1;
        entity.Quantity2 = d.Quantity2;
        entity.Quantity3 = d.Quantity3;
        entity.Quantity4 = d.Quantity4;
        entity.PackageType1 = d.PackageType1;
        entity.PackageType2 = d.PackageType2;
        entity.PackageType3 = d.PackageType3;
        entity.PackageType4 = d.PackageType4;
        entity.Quantity5 = d.Quantity5;
        entity.PackageType5 = d.PackageType5;
        entity.ShipperRef2 = d.ShipperRef2;
        entity.ConsigneeRef2 = d.ConsigneeRef2;
        entity.AgentId = d.AgentId;
        entity.AgentName = d.AgentName;
        entity.NotesToBePrinted = d.NotesToBePrinted;
        entity.Notes = d.Notes;
        entity.SentToCustomerAt = d.SentToCustomerAt;
        entity.IsCancelled = d.IsCancelled ?? entity.IsCancelled;
        entity.CancelledAt = d.CancelledAt;
        entity.IsActive = d.IsActive ?? true;
        entity.UpdatedAt = now;
        await repository.UpdateAsync(entity, cancellationToken);
        var result = await new GetQuoteByIdQueryHandler(repository, typeRepository).Handle(new GetQuoteByIdQuery(request.Id), cancellationToken);
        await actionLogClient.LogAsync("Quote updated", $"quote: {entity.QuoteNumber} • id: {entity.Id}", entity.ManagerId, entity.ManagerName, cancellationToken);
        return result;
    }
}
