// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Quotes.Infrastructure.Persistence;

#nullable disable

namespace Quotes.Infrastructure.Migrations
{
    [DbContext(typeof(QuotesDbContext))]
    [Migration("20260306000000_AddMinVatForDomesticAir")]
    partial class AddMinVatForDomesticAir
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
